version: '3.8'

services:
  # --- 后端服务 ---
  backend-service:  # 给它起个名字叫 backend-service
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rag_backend
    ports:
      - "8000:8000"
    volumes:
      # 挂载模型文件夹：直接使用你电脑上的 models 文件夹
      - ./models:/app/models
      # 挂载数据库和知识库
      - ./vector_db:/app/vector_db
      - ./knowledge_base:/app/knowledge_base
    environment:
      - PYTHONUNBUFFERED=1

  # --- 前端服务 ---
  frontend-service:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: rag_frontend
    ports:
      - "8501:8501"
    environment:
      # 关键！告诉前端去哪里找后端
      # http://backend-service:8000 中的 "backend-service" 对应上面的服务名
      - API_URL=http://backend-service:8000/ask
    depends_on:
      - backend-service # 等后端启动了再启动前端